export type SeedCategory = {
  slug: string; nameEn: string; nameAr: string;
  descriptionEn: string; descriptionAr: string; image: string;
  size: "normal" | "large" | "wide"; sortOrder: number;
};

export type SeedProduct = {
  slug: string; nameEn: string; nameAr: string;
  descriptionEn: string; descriptionAr: string;
  price: number; compareAtPrice: number | null; image: string; amazonUrl: string;
  categorySlug: string; badgeEn: string | null; badgeAr: string | null;
  rating: number; reviewsCount: number; stock: number; isFeatured: boolean;
};

export const seedCategories: SeedCategory[] = [
  { slug: "holders", nameEn: "Holders & Organizers", nameAr: "الحوامل والمنظمات", descriptionEn: "Practical and elegant ways to keep every surface tidy.", descriptionAr: "حلول عملية وأنيقة تخلي كل رحلة منظّم ومرتب.", image: "/images/categories/holders.jpg", size: "normal", sortOrder: 1 },
  { slug: "women-accessories", nameEn: "Women's Accessories", nameAr: "إكسسوارات حريمي", descriptionEn: "Chic accents that finish your everyday look.", descriptionAr: "لمسات أنيقة تكمل إطلالتك اليومية.", image: "/images/categories/women-accessories.jpg", size: "normal", sortOrder: 2 },
  { slug: "bathroom", nameEn: "Bathroom Accessories", nameAr: "مستلزمات الحمام", descriptionEn: "Modern sets that refresh your bathroom instantly.", descriptionAr: "أطقم عصرية تغيّر شكل حمامك بالكامل.", image: "/images/categories/bathroom.jpg", size: "large", sortOrder: 3 },
  { slug: "kitchen", nameEn: "Kitchen Supplies", nameAr: "أدوات المطبخ", descriptionEn: "Smart, beautiful tools for effortless cooking.", descriptionAr: "أدوات ذكية وأنيقة لتجربة طبخ مريحة.", image: "/images/categories/kitchen.jpg", size: "normal", sortOrder: 4 },
  { slug: "tissue-boxes", nameEn: "Tissue Boxes", nameAr: "علب المناديل", descriptionEn: "Luxury covers that add style to every table.", descriptionAr: "علب فاخرة تضيف شكل مختلف للطاولة.", image: "/images/categories/tissue-boxes.jpg", size: "normal", sortOrder: 5 },
  { slug: "decor", nameEn: "Modern Décor", nameAr: "ديكورات حديثة", descriptionEn: "Trendy pieces that give your home a modern soul.", descriptionAr: "قطع ديكورية تدي بيتك روح عصرية.", image: "/images/categories/decor.jpg", size: "wide", sortOrder: 6 },
];

export const seedProducts: SeedProduct[] = [
  { slug: "nordic-wooden-desk-organizer", nameEn: "Nordic Wooden Desk Organizer", nameAr: "منظم مكتب خشبي نورديك", descriptionEn: "Solid oak tray with four compartments.", descriptionAr: "صينية بلوط طبيعي بأربع خزانات.", price: 349, compareAtPrice: 429, image: "/images/products/holders-1.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ001", categorySlug: "holders", badgeEn: "Bestseller", badgeAr: "الأكثر مبيعًا", rating: 4.9, reviewsCount: 128, stock: 24, isFeatured: true },
  { slug: "minimal-pen-holder", nameEn: "Minimal Pen & Brush Holder", nameAr: "حامل أقلام مينيمال", descriptionEn: "Soft-matte ceramic holder.", descriptionAr: "حامل سيراميك بملمس مات ناعم.", price: 129, compareAtPrice: 169, image: "/images/products/holders-2.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ002", categorySlug: "holders", badgeEn: "New", badgeAr: "جديد", rating: 4.7, reviewsCount: 64, stock: 40, isFeatured: true },
  { slug: "oak-drawer-organizer-tray", nameEn: "Oak Drawer Organizer Tray", nameAr: "صنية تنظيم أدراج بلوط", descriptionEn: "Slim oak divider set.", descriptionAr: "طقم فواصل بلوط نحيف.", price: 219, compareAtPrice: null, image: "/images/products/holders-3.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ003", categorySlug: "holders", badgeEn: null, badgeAr: null, rating: 4.6, reviewsCount: 41, stock: 18, isFeatured: false },
  { slug: "solstice-gold-pendant-necklace", nameEn: "Solstice Gold Pendant Necklace", nameAr: "عقد سولستيس بقلادة ذهبية", descriptionEn: "Hand-finished sun pendant.", descriptionAr: "قلادة شمس مصنوعة بملمس نهائي يدوي.", price: 449, compareAtPrice: 549, image: "/images/products/women-1.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ004", categorySlug: "women-accessories", badgeEn: "Bestseller", badgeAr: "الأكثر مبيعًا", rating: 4.9, reviewsCount: 210, stock: 12, isFeatured: true },
  { slug: "lumiere-pearl-jewellery-set", nameEn: "Lumière Pearl Jewellery Set", nameAr: "طقم لوميير لؤلؤ", descriptionEn: "Pearl set with keepsake box.", descriptionAr: "طقم لؤلؤ ناعم مع علبة حفظ.", price: 689, compareAtPrice: null, image: "/images/products/women-2.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ005", categorySlug: "women-accessories", badgeEn: "New", badgeAr: "جديد", rating: 4.8, reviewsCount: 96, stock: 9, isFeatured: true },
  { slug: "amber-gift-box-set", nameEn: "Amber Gift Box Set", nameAr: "طقم هدايا أمبر", descriptionEn: "Curated jewellery gift box.", descriptionAr: "طقم مجوهرات في علبة هدايا.", price: 529, compareAtPrice: 629, image: "/images/products/women-3.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ006", categorySlug: "women-accessories", badgeEn: null, badgeAr: null, rating: 4.7, reviewsCount: 58, stock: 15, isFeatured: false },
  { slug: "marble-bathroom-vanity-set", nameEn: "Marble Bathroom Vanity Set", nameAr: "طقم حمام رخامي", descriptionEn: "Marble vanity set with gold details.", descriptionAr: "طقم رخامي بتفاصيل ذهبية.", price: 899, compareAtPrice: 1099, image: "/images/products/bathroom-1.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ007", categorySlug: "bathroom", badgeEn: "Bestseller", badgeAr: "الأكثر مبيعًا", rating: 4.9, reviewsCount: 174, stock: 8, isFeatured: true },
  { slug: "aero-chrome-bath-accessories", nameEn: "Aero Chrome Bath Accessories", nameAr: "إكسسوارات حمام كروم أيرو", descriptionEn: "Wall-mounted chrome bath rail.", descriptionAr: "رابل كروم مقاوم للصدأ.", price: 549, compareAtPrice: null, image: "/images/products/bathroom-2.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ008", categorySlug: "bathroom", badgeEn: null, badgeAr: null, rating: 4.6, reviewsCount: 73, stock: 22, isFeatured: false },
  { slug: "ceramic-soap-dispenser", nameEn: "Ceramic Soap Dispenser", nameAr: "موزع صابون سيراميك", descriptionEn: "Matte ceramic soap pump.", descriptionAr: "موزع صابون سيراميك بطلاء مطفي.", price: 179, compareAtPrice: 219, image: "/images/products/bathroom-3.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ009", categorySlug: "bathroom", badgeEn: "New", badgeAr: "جديد", rating: 4.8, reviewsCount: 88, stock: 35, isFeatured: true },
  { slug: "terra-ceramic-bowl-set", nameEn: "Terra Ceramic Bowl Set", nameAr: "طقم أوعية تيرا سيراميك", descriptionEn: "Three stackable stoneware bowls.", descriptionAr: "ثلاث أوعية ستونوير متدرجة.", price: 459, compareAtPrice: null, image: "/images/products/kitchen-1.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ010", categorySlug: "kitchen", badgeEn: "Bestseller", badgeAr: "الأكثر مبيعًا", rating: 4.8, reviewsCount: 132, stock: 20, isFeatured: true },
  { slug: "heritage-vintage-cutlery-set", nameEn: "Heritage Vintage Cutlery Set", nameAr: "طقم أدوات مائدة هيريتيج", descriptionEn: "Matte-gold cutlery set.", descriptionAr: "أدوات مائدة ذهبية مطفي.", price: 329, compareAtPrice: 399, image: "/images/products/kitchen-2.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ011", categorySlug: "kitchen", badgeEn: null, badgeAr: null, rating: 4.7, reviewsCount: 61, stock: 26, isFeatured: false },
  { slug: "forged-steel-knife-set", nameEn: "Forged Steel Knife Set", nameAr: "طقم سكاكين ستانلس مطروقة", descriptionEn: "Four forged knives with beech block.", descriptionAr: "أربع سكاكين مطروقة مع قاعدة خشب.", price: 749, compareAtPrice: 899, image: "/images/products/kitchen-3.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ012", categorySlug: "kitchen", badgeEn: "Sale", badgeAr: "خصم", rating: 4.9, reviewsCount: 118, stock: 11, isFeatured: true },
  { slug: "aura-gold-marble-tissue-box", nameEn: "Aura Gold Marble Tissue Box", nameAr: "علبة مناديل أورا رخام", descriptionEn: "Weighted marble tissue cover.", descriptionAr: "علبة مناديل بقاعدة رخام ثقيلة.", price: 259, compareAtPrice: 319, image: "/images/products/tissue-1.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ013", categorySlug: "tissue-boxes", badgeEn: "Bestseller", badgeAr: "الأكثر مبيعًا", rating: 4.8, reviewsCount: 149, stock: 30, isFeatured: true },
  { slug: "linen-tissue-box-cover", nameEn: "Linen Tissue Box Cover", nameAr: "غلاف مناديل كتان", descriptionEn: "Soft linen tissue cover with removable insert.", descriptionAr: "غلاف كتان ناعم بحشوة قابلة للإزالة.", price: 189, compareAtPrice: null, image: "/images/products/tissue-2.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ014", categorySlug: "tissue-boxes", badgeEn: "New", badgeAr: "جديد", rating: 4.6, reviewsCount: 47, stock: 28, isFeatured: false },
  { slug: "sable-minimal-ceramic-vase", nameEn: "Sable Minimal Ceramic Vase", nameAr: "مزهرية سيراميك مينيمال", descriptionEn: "Sculptural stoneware vase.", descriptionAr: "مزهرية ستونوير بشكل منحوت.", price: 299, compareAtPrice: null, image: "/images/products/decor-1.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ015", categorySlug: "decor", badgeEn: "Bestseller", badgeAr: "الأكثر مبيعًا", rating: 4.9, reviewsCount: 165, stock: 19, isFeatured: true },
  { slug: "halo-decorative-candle-holder", nameEn: "Halo Decorative Candle Holder", nameAr: "شمعدان هالو ديكوري", descriptionEn: "Layered brass candle halo.", descriptionAr: "حلقات نحاسية متدرجة للشمعة.", price: 219, compareAtPrice: 269, image: "/images/products/decor-2.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ016", categorySlug: "decor", badgeEn: null, badgeAr: null, rating: 4.7, reviewsCount: 82, stock: 24, isFeatured: false },
  { slug: "muse-ceramic-decor-pitcher", nameEn: "Muse Ceramic Decor Pitcher", nameAr: "إبريق سيراميك ديكوري", descriptionEn: "Gloss-white ceramic pitcher.", descriptionAr: "إبريق أبيض لامع بمقابض منحوتة.", price: 379, compareAtPrice: null, image: "/images/products/decor-3.jpg", amazonUrl: "https://www.amazon.eg/dp/B099XYZ017", categorySlug: "decor", badgeEn: "New", badgeAr: "جديد", rating: 4.8, reviewsCount: 54, stock: 14, isFeatured: true },
];
